### ISSUE TITLE
Speaking up about the things about this repo

### ISSUE THREAD

**Issue by MemeHoovy** [504brandon/Test-Engine-V1---FNF#11]
* Firstly
how many fucking coders did you get to work on this?? like you only need one coder to work on an engine, I know help can be appreciated but like, you don't wanna over sophisticate things. This is a good engine yes, but like, you don't wanna get too many coders on the team because, like I said, you'll just over sophisticate things.
* Secondly, this a pretty good engine ngl.
* Thirdly, 
(I know this is kinda hypocritical to what I said but) can I be part of the team please? It's your choice on whether you wanna invite me or not brandon, your opinion, not mine. 
* Fourthly, your a cool person and friend brandon :)))

And yes, I got github pro.

**Comment by Mackery6969** [comment]
yeah....
